NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

VERSION = "1.0.0"
SIGNING_KEY = "GD7JMUURLHHJKBWAK6FLDL7SWR72BEXGGEDWZ5JFRZNQ6VGACHRIWFMH"
WEB_AUTH_ENDPOINT = "https://stellar-sep-10.onrender.com/sep10/auth"

[DOCUMENTATION]
ORG_NAME = "Petseba Limited"
ORG_DBA = "Petseba"
ORG_URL = "https://petseba.com"
ORG_DESCRIPTION = "Petseba offers a toolbox with payment solutions making it easier to receive and make payments for your business."
ORG_PHYSICAL_ADDRESS = "annex hall room (1st floor), supreme court bar association building, 1000"
ORG_PHONE_NUMBER = "+8801733430911"
ORG_TWITTER = "petseba"
ORG_LINKEDIN = "https://www.linkedin.com/company/petseba/"
ORG_OFFICIAL_EMAIL = "support@petseba.com"
ORG_SUPPORT_EMAIL = "support@petseba.com"

[[PRINCIPALS]]
name = "Hijal"
email = "hijal@petseba.com"

[[PRINCIPALS]]
name = "Hijikesh Hijal"
email = "hijal@petseba.com"

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "live"
display_decimals = 3
name = "USD Coin"
desc = "USD Coin is digital stablecoin pegged to the United States dollar. USD Coin is managed by a consortium called Centre, which was founded by Circle and includes members from the cryptocurrency exchange Coinbase and Bitcoin mining company Bitmain, an investor in Circle."
image = "https://www.circle.com/hubfs/usdcoin-ondark.svg"
is_unlimited = true
is_asset_anchored = true
anchor_asset_type = "crypto"
anchor_asset = "USDC"